const fs=require('fs'),assert=require('assert');
const checklist=fs.readFileSync('www/checklist.html','utf8');
const storage=fs.readFileSync('www/photo-storage.js','utf8');
const manifest=fs.readFileSync('android/app/src/main/AndroidManifest.xml','utf8');
const activity=fs.readFileSync('android/app/src/main/java/br/com/docampo/smartfarm/MainActivity.java','utf8');
const shell=fs.readFileSync('www/app-shell.js','utf8');
const sql=fs.readFileSync('supabase-documentos.sql','utf8');
assert(checklist.includes("registerPlugin('PhotoCapture')"),'Botao Tirar foto deve chamar a camera nativa.');
assert(checklist.includes('Escolher da galeria'),'Galeria deve permanecer como opcao separada.');
assert(checklist.includes('salvarRascunhoFormulario()'),'Foto deve forcar salvamento imediato do rascunho.');
assert(storage.includes("DIR='checklist-photos'"),'Fotos devem ficar fora do banco textual.');
assert(storage.includes("Object.defineProperty(point,'foto'"),'Preview Base64 deve ser transiente e nao serializado.');
assert(storage.includes("storage/v1/object/"),'Foto deve possuir sincronizacao remota.');
assert(storage.includes('migrateDatabasePhotos'),'Fotos antigas devem ser migradas para fora do banco textual.');
assert(manifest.includes('android.permission.CAMERA'),'Android deve solicitar permissao da camera.');
assert(activity.includes('registerPlugin(PhotoCapturePlugin.class)'),'Plugin nativo da camera deve ser registrado.');
assert(shell.includes('backup.media'),'Backup deve transferir os arquivos de foto junto com os registros.');
assert(sql.includes("array['application/pdf','image/jpeg']"),'Bucket privado deve aceitar PDFs e fotos JPEG.');
console.log('checklist-photo-storage: ok');
