const assert=require('assert'),fs=require('fs'),vm=require('vm');
const store=new Map();const localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const context={console,localStorage,navigator:{onLine:false},crypto:{randomUUID:()=>Math.random().toString(36).slice(2)},CustomEvent:function(){},window:{dispatchEvent(){},addEventListener(){}},setTimeout(){}};context.window.window=context.window;
vm.createContext(context);vm.runInContext(fs.readFileSync('www/unified-db.js','utf8'),context);const db=context.window.DoCampoDB;
const old=new Date(Date.now()-8*86400000).toISOString(),recent=new Date(Date.now()-2*86400000).toISOString();
db.addDocument({id:'old',generatedAt:old,name:'Antigo'});db.addDocument({id:'recent',generatedAt:recent,name:'Recente'});
assert.strictEqual(db.archiveOldDocuments(7),1);assert.ok(db.get('documents','old').deletedAt);assert.ok(!db.get('documents','recent').deletedAt);
db.restore('documents','old');assert.ok(db.get('documents','old').restoredAt);assert.strictEqual(db.archiveOldDocuments(7),0);
db.softDelete('documents','old');assert.ok(db.hardDelete('documents','old'));assert.strictEqual(db.get('documents','old'),null);
console.log('document-retention: ok');
